// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "C:/Users/tarde/Documents/Desarrollos/infoMaps/citySights/app.config";
import type { default as appConfig1 } from "C:/Users/tarde/Documents/Desarrollos/infoMaps/citySights/node_modules/.pnpm/@nuxt-awesome+theme@2.0.12_nuxt@3.10.1_vite@5.1.1_vue@3.4.18/node_modules/@nuxt-awesome/theme/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}